export interface Drawing {
	id: string;
	userId: string;
	username: string;
	imageUrl: string;
	referenceUrl?: string;
	category: string;
	duration: number;
	createdAt: string;
	likes: number;
	comments: number;
	showWithReference: boolean;
}
export const currentUserDrawings: Drawing[] = [
	{
		id: "1",
		userId: "current",
		username: "You",
		imageUrl: "figure-sketch-practice",
		referenceUrl: "figure-reference-pose",
		category: "Figure Drawing",
		duration: 300,
		createdAt: "2026-02-09T10:30:00",
		likes: 24,
		comments: 4,
		showWithReference: true,
	},
	{
		id: "2",
		userId: "current",
		username: "You",
		imageUrl: "hand-study-sketch",
		category: "Hands",
		duration: 120,
		createdAt: "2026-02-09T09:15:00",
		likes: 18,
		comments: 14,
		showWithReference: false,
	},
	{
		id: "3",
		userId: "current",
		username: "You",
		imageUrl: "still-life-drawing",
		referenceUrl: "still-life-objects",
		category: "Still Life",
		duration: 600,
		createdAt: "2026-02-08T14:20:00",
		likes: 31,
		comments: 10,
		showWithReference: true,
	},
];

export const exploreDrawings: Drawing[] = [
	{
		id: "e1",
		userId: "3",
		username: "Sarah Chen",
		imageUrl: "portrait-sketch-woman",
		referenceUrl: "portrait-reference-woman",
		category: "Portraits",
		duration: 900,
		createdAt: "2026-02-09T08:00:00",
		likes: 156,
		comments: 139,
		showWithReference: true,
	},
	{
		id: "e2",
		userId: "4",
		username: "James Wilson",
		imageUrl: "dynamic-fight-pose",
		category: "Fights",
		duration: 420,
		createdAt: "2026-02-09T07:30:00",
		likes: 203,
		comments: 53,
		showWithReference: false,
	},
	{
		id: "e3",
		userId: "6",
		username: "Alex Kim",
		imageUrl: "hand-gesture-study",
		referenceUrl: "hand-gesture-reference",
		category: "Hands",
		duration: 180,
		createdAt: "2026-02-08T16:45:00",
		likes: 89,
		comments: 20,
		showWithReference: true,
	},
	{
		id: "e4",
		userId: "8",
		username: "Noah Brown",
		imageUrl: "figure-gesture-drawing",
		category: "Figure Drawing",
		duration: 240,
		createdAt: "2026-02-08T15:20:00",
		likes: 142,
		comments: 52,
		showWithReference: false,
	},
	{
		id: "e5",
		userId: "5",
		username: "Emily Rodriguez",
		imageUrl: "detailed-still-life",
		referenceUrl: "still-life-setup",
		category: "Still Life",
		duration: 1200,
		createdAt: "2026-02-08T12:00:00",
		likes: 267,
		comments: 102,
		showWithReference: true,
	},
	{
		id: "e6",
		userId: "7",
		username: "Olivia Martinez",
		imageUrl: "action-pose-sketch",
		category: "Fights",
		duration: 300,
		createdAt: "2026-02-08T10:30:00",
		likes: 178,
		comments: 77,
		showWithReference: false,
	},
	{
		id: "e7",
		userId: "9",
		username: "Sophia Lee",
		imageUrl: "abstract-art",
		category: "Still Life",
		duration: 480,
		createdAt: "2026-02-07T18:20:00",
		likes: 194,
		comments: 65,
		showWithReference: false,
	},
	{
		id: "e8",
		userId: "10",
		username: "Liam Taylor",
		imageUrl: "comic-style",
		category: "Portraits",
		duration: 360,
		createdAt: "2026-02-07T14:10:00",
		likes: 221,
		comments: 88,
		showWithReference: false,
	},
	{
		id: "e9",
		userId: "1",
		username: "Dan",
		imageUrl: "character-design",
		referenceUrl: "character-reference",
		category: "Figure Drawing",
		duration: 720,
		createdAt: "2026-02-07T09:45:00",
		likes: 312,
		comments: 124,
		showWithReference: true,
	},
	{
		id: "e10",
		userId: "2",
		username: "Denis",
		imageUrl: "quick-gesture",
		category: "Figure Drawing",
		duration: 60,
		createdAt: "2026-02-06T21:30:00",
		likes: 98,
		comments: 31,
		showWithReference: false,
	},
	{
		id: "e11",
		userId: "3",
		username: "Sarah Chen",
		imageUrl: "nature-watercolor",
		category: "Still Life",
		duration: 1080,
		createdAt: "2026-02-06T16:15:00",
		likes: 245,
		comments: 96,
		showWithReference: false,
	},
	{
		id: "e12",
		userId: "4",
		username: "James Wilson",
		imageUrl: "action-sequence",
		category: "Fights",
		duration: 540,
		createdAt: "2026-02-06T11:20:00",
		likes: 187,
		comments: 73,
		showWithReference: false,
	},
	{
		id: "e13",
		userId: "5",
		username: "Emily Rodriguez",
		imageUrl: "environment-concept",
		referenceUrl: "environment-reference",
		category: "Still Life",
		duration: 1500,
		createdAt: "2026-02-05T19:00:00",
		likes: 334,
		comments: 147,
		showWithReference: true,
	},
	{
		id: "e14",
		userId: "6",
		username: "Alex Kim",
		imageUrl: "manga-character",
		category: "Portraits",
		duration: 420,
		createdAt: "2026-02-05T14:30:00",
		likes: 276,
		comments: 112,
		showWithReference: false,
	},
	{
		id: "e15",
		userId: "7",
		username: "Olivia Martinez",
		imageUrl: "portrait-lighting",
		category: "Portraits",
		duration: 600,
		createdAt: "2026-02-05T09:15:00",
		likes: 198,
		comments: 84,
		showWithReference: false,
	},
	{
		id: "e16",
		userId: "8",
		username: "Noah Brown",
		imageUrl: "pixel-character",
		category: "Portraits",
		duration: 240,
		createdAt: "2026-02-04T20:45:00",
		likes: 223,
		comments: 91,
		showWithReference: false,
	},
	{
		id: "e17",
		userId: "9",
		username: "Sophia Lee",
		imageUrl: "abstract-composition",
		category: "Still Life",
		duration: 900,
		createdAt: "2026-02-04T15:30:00",
		likes: 167,
		comments: 58,
		showWithReference: false,
	},
	{
		id: "e18",
		userId: "10",
		username: "Liam Taylor",
		imageUrl: "comic-panel",
		category: "Portraits",
		duration: 480,
		createdAt: "2026-02-04T10:20:00",
		likes: 201,
		comments: 79,
		showWithReference: false,
	},
];

export const referenceCategories = [
	{ id: "figure", name: "Figure Drawing", icon: "👤" },
	{ id: "hands", name: "Hands", icon: "✋" },
	{ id: "still-life", name: "Still Life", icon: "🏺" },
	{ id: "fights", name: "Fights", icon: "🥊" },
	{ id: "portraits", name: "Portraits", icon: "👨" },
	{ id: "animals", name: "Animals", icon: "🦁" },
];